#Introducing the main Interface: (Class Name):
#Use tab spacings for all indentations
AL
<AL>:
    #right/left/center
    anchor_x: "center"                #at least 1 (x or y)
    #bottom/top/center
    anchor_y: "center"
    BoxLayout:
        size_hint: 0.5,0.5
        Button:
            text: "A"
        Button:
            text: "B"
        Button:
            text:"C"
        Button:
            text:"D"