#Introducing the main Interface: (Class Name):
#Use tab spacings for all indentations
GL
<GL>:
    cols: 3
    row:3   #Atleast one parameter must be specified (rows or columns or both)
    Button:
        text:"A"
    Label:
        text:"B"
    Button:
        text:"C"
    Label:
        text:"D"
    Button:
        text:"E"
    Label:
        text:"F"
    Button:
        text:"G"
    Label:
        text:"H"
    Button:
        text:"I"
