Images
<Images>:
    #right/left/center
    anchor_x: "center"                #at least 1 (x or y)
    #bottom/top/center
    anchor_y: "center"
    BoxLayout:
        size_hint: 0.8,0.8
        spacing: "20dp"
        Image:
            source: "Images/Space.png"
        Image:
            source: "Images/Lynx.png"
        Image:
            source:"Images/Waterfall.png"
        Image:
            source:"Images/Pebbles.png"